const input=document.getElementById('customerName');const btn=document.getElementById('sendBtn');const choice=document.getElementById('choice');const choicePreview=document.getElementById('choicePreview');const choiceName=document.getElementById('choiceName');let selected=null;let publicConfig=window.FLORENTINO_CONFIG||{};
function typed(){return input.value.trim()||'Florentino Imports'}
function fitFontPreview(el){let size=34;el.style.fontSize=size+'px';while(el.scrollWidth>el.clientWidth&&size>13){size--;el.style.fontSize=size+'px'}}
function refreshNames(){document.querySelectorAll('.font-preview').forEach(el=>{el.textContent=typed();requestAnimationFrame(()=>fitFontPreview(el))});if(selected)choicePreview.textContent=typed()}
function bindCards(){const cards=[...document.querySelectorAll('.font-card')];cards.forEach(card=>card.onclick=()=>{cards.forEach(c=>c.classList.remove('on'));card.classList.add('on');selected={id:card.dataset.id,font:card.dataset.font};choice.classList.remove('hidden');choicePreview.textContent=typed();choicePreview.style.fontFamily='"'+selected.font+'", sans-serif';choiceName.textContent='Fonte '+String(selected.id).padStart(2,'0')+' · '+selected.font;btn.disabled=false})}
function loadGoogleFonts(fonts){const native=fonts.filter(f=>!f.custom);const families=native.map(f=>'family='+encodeURIComponent(f.name).replace(/%20/g,'+')).join('&');if(!families)return;const link=document.createElement('link');link.id='dynamic-public-fonts';link.rel='stylesheet';link.href='https://fonts.googleapis.com/css2?'+families+'&display=swap';document.head.appendChild(link)}
async function loadCustomFonts(fonts){for(const f of fonts.filter(f=>f.custom&&f.url)){try{const face=new FontFace(f.name,`url(${f.url})`);await face.load();document.fonts.add(face)}catch(e){console.warn('Fonte personalizada',f.name,e)}}}
async function renderPublicFonts(fonts){const grid=document.getElementById('fontGrid');if(!grid)return;selected=null;btn.disabled=true;choice.classList.add('hidden');grid.innerHTML='';loadGoogleFonts(fonts);await loadCustomFonts(fonts);fonts.forEach(f=>{const card=document.createElement('button');card.className='font-card';card.dataset.id=String(f.id);card.dataset.font=f.name;const id=document.createElement('span');id.className='font-id';id.textContent=String(f.id).padStart(2,'0');const preview=document.createElement('span');preview.className='font-preview';preview.style.fontFamily='"'+f.name+'", sans-serif';preview.textContent=typed();const name=document.createElement('span');name.className='font-name';name.textContent=f.name;card.append(id,preview,name);grid.appendChild(card)});bindCards();refreshNames();if(document.fonts&&document.fonts.ready)document.fonts.ready.then(refreshNames)}
async function loadPublicConfig(){try{let response,config;if(['localhost','127.0.0.1'].includes(location.hostname)){const session=await fetch('/api/session',{cache:'no-store'}).then(r=>r.json());const options={cache:'no-store',headers:{'X-Local-Session':session.token}};const localResponse=await fetch('/api/client-config',options);const local=localResponse.ok?await localResponse.json():null;response=await fetch('/api/client-config/remote',options);if(response.ok){const remote=await response.json();config=local?.remoteSha===remote.sha?local:remote.config;config.fonts=config.fonts.map(f=>({...f,url:f.data?'data:font/'+(f.ext||'ttf')+';base64,'+f.data:f.url?'https://florentinoimports67-stack.github.io/florentino-fontes/'+f.url:undefined}))}else{response=await fetch('/api/client-config',options);config=await response.json();config.fonts=config.fonts.map(f=>({...f,url:f.data?'data:font/'+(f.ext||'ttf')+';base64,'+f.data:f.url?'https://florentinoimports67-stack.github.io/florentino-fontes/'+f.url:undefined}))}}else{response=await fetch('./font-config.json?t='+Date.now(),{cache:'no-store'});config=await response.json()}if(!response.ok)throw new Error('HTTP '+response.status);if(config.whatsapp)publicConfig.whatsapp=config.whatsapp;if(Array.isArray(config.fonts))await renderPublicFonts(config.fonts)}catch(err){console.error('Falha ao carregar font-config.json',err);bindCards();refreshNames()}}
input.addEventListener('input',refreshNames);btn.addEventListener('click',()=>{if(!selected)return;const nome=input.value.trim();if(!nome){input.focus();alert('Digite o nome para gravação.');return}const numero=String(publicConfig.whatsapp||'').replace(/\D/g,'');const inicio=publicConfig.mensagemInicial||'Olá! Escolhi minha personalização na página da Florentino Imports.';const msg=inicio+'\n\nNome para gravação: '+nome+'\nFonte: '+String(selected.id).padStart(2,'0')+' · '+selected.font;window.open((numero?'https://wa.me/'+numero:'https://wa.me/')+'?text='+encodeURIComponent(msg),'_blank')});window.addEventListener('resize',refreshNames);loadPublicConfig();